services_dict = {
    'mother_and_son': 'Мама и малыш',
    'family_psychologist': 'Семейный психолог',
    'new_year': 'Новый год',
    'dool_training': 'Кукловедение',
    'iso_modeling': 'Изолепка',
    'speech_launch': 'Говорилка',
    'baby_fitness': 'Baby fitnes',
    'tyap_lyap': 'Тяп-ляп',
    'sand_table': 'Песочный стол',
    'school_preparation': 'Подготовка к школе',
    'health_spine': 'Здоровье спины и стопы',
    'speech_pathologist': 'Логопед',
    'child_dance': 'Детская хореография',
    'school_art': 'Школа живописи',
    'baby_and_glade': 'Малышники и полянки',
    'modern_dance': "Современные танцы",
    'reading': 'Чтение',
    'math_academy': 'Математическая академия',
    'english': 'Английский язык',
    'acrobatics': 'Акробатика',
    'summer_club': 'Летний клуб',
    'future_first_schoolboy': 'Будущий первоклассник',
    'after_school_program': 'Продленка',
    #'speed_reading': 'Скорочтение',
    'table_multiplication': 'Таблица умножения',
    'literacy': 'Грамотность',
    'theatre_studio': 'Театральная студия',
    'ready_for_school': 'Готов к школе',
}
